#!/bin/bash

SERVICE_DIR="/etc/systemd/system/rtspcam.service"
SERVICE_NAME="rtspcam.service"

echo "[*] Copying $SERVICE_NAME to $SERVICE_DIR"
sudo cp rtspcam.service $SERVICE_DIR


echo "[*] Reloading systemd configuration..."
sudo systemctl daemon-reload

echo "[+] Enabling the $SERVICE_NAME service..."
sudo systemctl enable $SERVICE_NAME

sudo systemctl start $SERVICE_NAME

echo "[+] $SERVICE_NAME has been enabled and started."
