#!/bin/bash

SERVICE_DIR="/etc/systemd/system"
SERVICE_NAME="rtsp.service"

echo "[*] Copying $SERVICE_NAME to $SERVICE_DIR"
sudo cp /path/to/your/rtsp.service $SERVICE_DIR


echo "[*] Reloading systemd configuration..."
sudo systemctl daemon-reload

echo "[+] Enabling the $SERVICE_NAME service..."
sudo systemctl enable $SERVICE_NAME

sudo systemctl start $SERVICE_NAME

echo "[+] $SERVICE_NAME has been enabled and started."
